#' Launch the dtsmartr Data Explorer in your default Web Browser
#'
#' Launches a temporary, lightweight Shiny server in the background and opens the
#' interactive grid in your default external web browser. This bypasses local
#' browser origin security policies (CORS) that block `file://` resources.
#'
#' @param data A `data.frame` to explore, or `NULL` (default) to launch the
#'   Zero-Code Data Ingestion Wizard.
#' @param port Optional port number. If `NULL` (default), a free port is chosen automatically.
#' @param options Named list of UI options generated by [dtsmartr_options()].
#'
#' @details
#' ## Zero-Code Ingestion Wizard (Wizard Mode)
#' When `data = NULL` (default), the Shiny server boots into Wizard Mode. An
#' interactive interface (powered by the `datamods` package) allows users to
#' select from two distinct tabs:
#' - **External file**: Drag-and-drop or select `.csv`, `.xlsx`, `.sas7bdat`, or `.rds` files.
#' - **pharmaverse ADaM datasets**: Explore standard clinical ADaM datasets directly from the `pharmaverseadam` package environment.
#'
#' Once a file is successfully uploaded or selected, the wizard parses the dataset and feeds it
#' directly into the React-powered virtualized grid explorer.
#'
#' @importFrom shiny fluidPage tags HTML runApp conditionalPanel div h2 p reactive req outputOptions tabsetPanel tabPanel icon
#' @importFrom datamods import_file_ui import_file_server import_globalenv_ui import_globalenv_server
#'
#' @export
#'
#' @examples
#' if (interactive()) {
#'   # 1. Launch wizard mode to upload local files
#'   dtsmart_launch()
#'
#'   # 2. Launch directly with a dataset
#'   dtsmart_launch(mtcars)
#' }
dtsmart_launch <- function(
    data    = NULL,
    port    = NULL,
    options = dtsmartr_options()
) {

  if (!is.null(data)) {
    # ── Direct Mode: Render dataset immediately ──────────────────────────────
    if (!is.data.frame(data)) {
      stop("`data` must be a data.frame or NULL", call. = FALSE)
    }

    ds_name <- deparse(substitute(data))
    if (length(ds_name) > 1) ds_name <- paste(ds_name, collapse = "")
    if (nchar(ds_name) > 40 || grepl("[\\\\(\\\\)\\\\{\\\\}]", ds_name)) {
      ds_name <- "df"
    }

    ui <- shiny::fluidPage(
      title = paste("dtsmartr -", ds_name),
      shiny::tags$head(
        shiny::tags$style(shiny::HTML("
          body { margin: 0; padding: 0; overflow: hidden; background: #fff; }
          #grid { height: 100vh !important; }
        "))
      ),
      dtsmartrOutput("grid", width = "100%", height = "100vh")
    )

    server <- function(input, output, session) {
      output$grid <- renderDtsmartr({
        dtsmartr(data, datasetName = ds_name, options = options)
      })
    }

  } else {
    # ── Wizard Mode: Custom File & ADaM Ingestion ──────────────────────────────
    theme_val <- if (requireNamespace("bslib", quietly = TRUE)) {
      bslib::bs_theme(version = 5, bootswatch = "flatly")
    } else {
      NULL
    }

    ui <- shiny::fluidPage(
      theme = theme_val,
      title = "dtsmartr Ingestion Wizard",
      shiny::tags$head(
        shiny::tags$style(shiny::HTML("
          body { background: #f8fafc; font-family: system-ui, -apple-system, sans-serif; }
          .wizard-card {
            max-width: 900px; margin: 60px auto; padding: 40px;
            background: #ffffff; border-radius: 16px;
            border: 1px solid #e2e8f0;
            box-shadow: 0 15px 35px -5px rgba(0, 0, 0, 0.05), 0 10px 10px -5px rgba(0, 0, 0, 0.02);
          }
          .nav-tabs {
            border-bottom: 2px solid #e2e8f0;
            margin-bottom: 25px;
            justify-content: center;
            gap: 15px;
          }
          .nav-item .nav-link {
            font-weight: 600;
            color: #64748b;
            border: none;
            border-bottom: 3px solid transparent;
            padding: 10px 20px;
            font-size: 15px;
          }
          .nav-item .nav-link.active {
            color: #2563eb;
            border-bottom: 3px solid #2563eb;
            background: transparent;
          }
          #grid { height: 100vh !important; }
        "))
      ),
      # UI visible only when no data is loaded
      shiny::conditionalPanel(
        condition = "!output.has_data",
        shiny::div(
          class = "wizard-card",
          shiny::h2("dtsmartr Data Ingestion Wizard",
                    style = "font-weight: 800; color: #0f172a; margin-bottom: 8px; text-align: center; letter-spacing: -0.025em;"),
          shiny::p("Explore your own datasets or clinical ADaM datasets instantly.",
                   style = "color: #64748b; text-align: center; margin-bottom: 35px; font-size: 15px;"),
          
          shiny::tabsetPanel(
            id = "import_tabs",
            shiny::tabPanel(
              title = "External file",
              shiny::tags$br(),
              datamods::import_file_ui(
                id = "file_importer",
                title = NULL,
                file_extensions = c(".csv", ".xlsx", ".sas7bdat", ".rds")
              )
            ),
            shiny::tabPanel(
              title = "pharmaverse ADaM datasets",
              shiny::tags$br(),
              datamods::import_globalenv_ui(
                id = "env_importer",
                globalenv = FALSE,
                packages = "pharmaverseadam",
                title = NULL
              )
            )
          )
        )
      ),
      # Fullscreen UI visible when data is loaded
      shiny::conditionalPanel(
        condition = "output.has_data",
        shiny::div(
          style = "position: fixed; inset: 0; overflow: hidden; background: #fff;",
          dtsmartrOutput("grid", width = "100%", height = "100vh")
        )
      )
    )

    server <- function(input, output, session) {
      # File Uploader Sub-module
      file_data <- datamods::import_file_server(
        id            = "file_importer",
        trigger_return = "change",
        btn_show_data = FALSE
      )

      # ADaM Environment/Package Sub-module
      env_data <- datamods::import_globalenv_server(
        id            = "env_importer",
        trigger_return = "change",
        btn_show_data = FALSE
      )

      # Reactive values to hold selected dataframe and name
      imported <- shiny::reactiveValues(data = NULL, name = NULL)

      shiny::observeEvent(file_data$data(), {
        shiny::req(file_data$data())
        imported$data <- file_data$data()
        imported$name <- file_data$name()
      })

      shiny::observeEvent(env_data$data(), {
        shiny::req(env_data$data())
        imported$data <- env_data$data()
        imported$name <- env_data$name()
      })

      has_data <- shiny::reactive({
        !is.null(imported$data) && is.data.frame(imported$data)
      })

      output$has_data <- shiny::reactive({
        has_data()
      })
      shiny::outputOptions(output, "has_data", suspendWhenHidden = FALSE)

      output$grid <- renderDtsmartr({
        shiny::req(has_data())
        dtsmartr(imported$data, datasetName = imported$name, options = options)
      })
    }
  }

  # Launch default external browser on the background Shiny server
  shiny::runApp(
    appDir         = list(ui = ui, server = server),
    launch.browser = TRUE,
    port           = port,
    quiet          = TRUE
  )
}
